# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя, Фамилия')),
                ('group_in', models.CharField(max_length=100, verbose_name='Группы')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.CharField(max_length=1000, verbose_name='Описание теста'),
        ),
    ]
