# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20170923_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_in',
            field=models.CharField(blank=True, max_length=100, verbose_name='Группы'),
        ),
    ]
