# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import test_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20170923_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=100, verbose_name='Группа')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='group',
            field=models.CharField(max_length=100, verbose_name=test_app.models.Group),
        ),
    ]
