# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20170924_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='group',
        ),
        migrations.AddField(
            model_name='test',
            name='groups',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='test_app.Group'),
        ),
    ]
