# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20170924_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='groups',
        ),
        migrations.AddField(
            model_name='test',
            name='groups',
            field=models.ManyToManyField(default='', to='test_app.Group'),
        ),
    ]
