# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20170924_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(blank=True, max_length=1000000, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='test',
            name='groups',
            field=models.ManyToManyField(blank=True, default='', to='test_app.Group'),
        ),
    ]
