# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_test_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 25, 13, 24, 47, 925023, tzinfo=utc), null=True),
        ),
    ]
