# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_auto_20170925_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_in',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, default='', to='test_app.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(blank=True, max_length=1000000, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 25, 19, 33, 40, 956545, tzinfo=utc), null=True),
        ),
    ]
