# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20170925_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст сообщения')),
                ('groups', models.ManyToManyField(blank=True, default='', to='test_app.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 25, 21, 32, 56, 411285, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Описание теста'),
        ),
    ]
