# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_auto_20170926_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 25, 21, 38, 33, 940919, tzinfo=utc), null=True)),
                ('user_id', models.ManyToManyField(blank=True, default='', to='test_app.User')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 25, 21, 38, 33, 938476, tzinfo=utc), null=True),
        ),
    ]
