# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0020_auto_20170927_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 27, 10, 6, 47, 907573, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 27, 10, 6, 47, 909419, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 27, 10, 6, 47, 904876, tzinfo=utc), null=True),
        ),
    ]
